version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.1
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      TYPESENSE_API_KEY: xyz123
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"

volumes:
  postgres_data:
  typesense_data: